#!/usr/bin/env node
// Keeps the repo and the BITFire design system (a Claude Design artifact) in step.
//
// Ownership: this repo owns the token VALUES. The artifact's token view and the
// skill's token table are published FROM packages/tokens/src/tokens.json and are
// never hand-edited. The brand book and prose live in the artifact only.
//
//   export <dir>   write <dir>/tokens.json (byte-identical to the repo's) and
//                  <dir>/token-table.md (every colour token, both themes), for
//                  publishing to the artifact and for the skill's table.
//   check <file>   compare a saved copy of the artifact's project/tokens.json with
//                  the repo's; exit 0 only if the bytes match, and otherwise name
//                  each token that differs.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SRC = fileURLToPath(new URL('../packages/tokens/src/tokens.json', import.meta.url));
const sha = (b) => createHash('sha256').update(b).digest('hex');
const [cmd, arg] = process.argv.slice(2);

const usage = () => {
  console.error('usage: design-system.mjs export <dir> | check <artifact-tokens.json>');
  process.exit(2);
};
if (!cmd || !arg || !['export', 'check'].includes(cmd)) usage();

const repoBytes = readFileSync(SRC);

if (cmd === 'export') {
  const T = JSON.parse(repoBytes.toString('utf8'));
  mkdirSync(arg, { recursive: true });
  writeFileSync(join(arg, 'tokens.json'), repoBytes);
  const row = (t) => {
    const v = t.value;
    return typeof v === 'string' ? `| \`${t.name}\` | ${v} | ${v} |` : `| \`${t.name}\` | ${v.dark ?? ''} | ${v.light ?? ''} |`;
  };
  const table = [
    '<!-- Generated by tools/design-system.mjs from packages/tokens/src/tokens.json. Do not edit by hand. -->',
    `<!-- source sha256 ${sha(repoBytes)} -->`,
    '',
    `Colour tokens (${T.color.tokens.length}). Dark is the primary theme. A token with one value is theme-independent.`,
    '',
    '| Token | Dark | Light |',
    '| --- | --- | --- |',
    ...T.color.tokens.map(row),
    '',
  ].join('\n');
  writeFileSync(join(arg, 'token-table.md'), table);
  console.error(`ok: wrote tokens.json (${repoBytes.length} bytes, sha256 ${sha(repoBytes).slice(0, 12)}) and token-table.md (${T.color.tokens.length} colour tokens) to ${arg}`);
  process.exit(0);
}

// check
let copyBytes;
try {
  copyBytes = readFileSync(arg);
} catch (e) {
  console.error(`design-system check: cannot read ${arg}: ${e.message}`);
  process.exit(2);
}
if (Buffer.compare(copyBytes, repoBytes) === 0) {
  console.error(`ok: the artifact copy is byte-identical to the repo (sha256 ${sha(repoBytes).slice(0, 12)})`);
  process.exit(0);
}

let repo, copy;
try {
  repo = JSON.parse(repoBytes.toString('utf8'));
  copy = JSON.parse(copyBytes.toString('utf8'));
} catch (e) {
  console.error(`DRIFT: ${arg} is not valid JSON (${e.message})`);
  process.exit(1);
}
// Flatten to path -> value, keyed by token name where a list holds named tokens.
const flat = (o, p = '', out = {}) => {
  if (Array.isArray(o)) o.forEach((v, i) => flat(v, `${p}/${v && typeof v === 'object' && v.name ? v.name : `[${i}]`}`, out));
  else if (o && typeof o === 'object') for (const [k, v] of Object.entries(o)) flat(v, `${p}/${k}`, out);
  else out[p] = o;
  return out;
};
const R = flat(repo), C = flat(copy);
const onlyRepo = Object.keys(R).filter((k) => !(k in C));
const onlyCopy = Object.keys(C).filter((k) => !(k in R));
const differ = Object.keys(R).filter((k) => k in C && R[k] !== C[k]);
const show = (label, keys) => keys.length && (console.error(`  ${label} (${keys.length}):`), keys.slice(0, 25).forEach((k) => console.error(`    ${k}`)), keys.length > 25 && console.error(`    ... and ${keys.length - 25} more`));
const same = !onlyRepo.length && !onlyCopy.length && !differ.length;
console.error(`DRIFT: the artifact copy is not byte-identical to the repo (repo ${repoBytes.length} bytes, copy ${copyBytes.length}).`);
if (same) console.error('  The content is the same; only the formatting differs. Republish from the repo to fix it.');
show('in the repo only', onlyRepo);
show('in the artifact copy only', onlyCopy);
show('value differs', differ);
console.error('The repo owns token values: republish the artifact from the repo (run: node tools/design-system.mjs export <dir>), never edit the artifact copy.');
process.exit(1);
